### editorconfig-vim ###
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

### colorschemes ###
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
'''

### airline ###
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='gruvbox'
'''

### Gitのステータスをファイル左横に表示するやつ ###
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap ]h <Plug>(GitGutterNextHunk)
nnoremap [h <Plug>(GitGutterPrevHunk)
nnoremap ghs <Plug>(GitGutterStageHunk)
nnoremap ghu <Plug>(GitGutterUndoHunk)
nnoremap ghp <Plug>(GitGutterPreviewHunk)
'''

### vim上でGit操作可能にするやつ ###
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <Leader>ga :G add %:p<CR><CR>
nnoremap <Leader>gc :G commit<CR><CR>
nnoremap <Leader>gs :G status<CR>
nnoremap <Leader>gp :G push<CR>
nnoremap <Leader>gd :G diff<CR>
nnoremap <Leader>gl :G log<CR>
nnoremap <Leader>glo :G log --oneline<CR>
nnoremap <Leader>gb :G blame<CR>
'''

### ファイラー ###
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
nnoremap <Leader>e <cmd>Fern . -reveal=%<CR>
'''

### 「閉じ」文字を補完するやつ ###
[[plugins]]
repo = 'cohama/lexima.vim'

### 「囲み」文字を簡単に操作するやつ ###
[[plugins]]
repo = 'tpope/vim-surround'

### JSONを扱いやすくするやつ ###
[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
set conceallevel=2
set concealcursor=niv
let g:vim_json_syntax_conceal = 0
'''

### コメントアウト・解除を簡単にするやつ ###
[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'

nmap <C-c> <Plug>NERDCommenterToggle
vmap <C-c> <Plug>NERDCommenterToggle<CR>gv
'''

### fuzzy finder ###
[[plugins]]
repo = 'junegunn/fzf'
build = 'bash install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <Leader>z :FZF<CR>
nnoremap <Leader>r :Rg
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>W :Windows<CR>
nnoremap <Leader>H :History<CR>
'''

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'
hook_add = '''
nnoremap <silent>//     <cmd>FzfPreviewLinesRpc<CR>
nnoremap <silent><C-f>  <cmd>FzfPreviewBufferLinesRpc<CR>
nnoremap <silent><C-p>  <cmd>FzfPreviewProjectFilesRpc<CR>

"nnoremap <silent>//     :BLines<CR>
"nnoremap <silent><C-f>  :Lines<CR>
"nnoremap <silent><C-p>  :Files<CR>
'''

### 選択範囲を段階的に広げるやつ ###
[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap V <Plug>(expand_region_shrink)
'''

### linter ###
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines'],
\   'c': ['clang-format'],
\   'cpp': ['clang-format'],
\ }
'''

### ハイライトを補強するやつ ###
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 1
# hook_post_update = 'TSUpdate'
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'go',
        'html',
        'javascript',
        'json',
        'python',
        'ruby',
        'rust',
        'toml',
        'typescript',
    },
    highlight = {
        enable = true,
        disable = {},
    },
}
EOF
'''

### アイコン提供するやつ ###
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

### タブ操作を簡単にするやつ ###
[[plugins]]
repo = 'romgrk/barbar.nvim'

### 縦スクロールバーを表示するやつ ###
[[plugins]]
repo = 'dstein64/nvim-scrollview'
hook_add = '''
" https://github.com/dstein64/nvim-scrollview/issues/10
command Bdelete silent! ScrollViewDisable | bdelete | silent! ScrollViewEnable
nnoremap <silent><C-w> <cmd>Bdelete<CR>
'''

### yank範囲をハイライトするやつ ###
[[plugins]]
repo = 'machakann/vim-highlightedyank'

### フォーカス移動を自由自在にするやつ ###
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
noremap  <Leader>f <Plug>(easymotion-bd-f)
nnoremap <Leader>f <Plug>(easymotion-overwin-f)
nnoremap <Leader>s <Plug>(easymotion-overwin-f2)
noremap  <Leader>L <Plug>(easymotion-bd-jk)
nnoremap <Leader>L <Plug>(easymotion-overwin-line)
noremap  <Leader>w <Plug>(easymotion-bd-w)
nnoremap <Leader>w <Plug>(easymotion-overwin-w)
'''
