[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = ['BufRead']
depends = ['neomru.vim']
hook_post_source = '''
call denite#custom#var('file/rec', 'command', 
    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#source('file_mru', 'matchers', 
    \ ['matcher/fuzzy', 'matcher/project_files'])
call denite#custom#var('file/rec', 'command',
    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command',
    \ ['git', 'ls-files', '-co', '--exclude-standard'])
'''

################################################
# Ruby
################################################

[[plugins]] # def end の自動入力
repo = 'tpope/vim-endwise.git'
on_ft = ['ruby', 'eruby']
hook_post_source = '''
let g:endwise_no_mappings = v:true
'''

[[plugins]] # Railsプロジェクト用プラグイン
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']
hook_add = '''
let g:rails_no_abbreviations = 1
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']
hook_add = '''
let g:html5_event_handler_attributes_complete = 0
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['html', 'css']

[[plugins]]
repo = "fatih/vim-go"
on_ft = ['go']

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ['toml']

[[plugins]]
repo = "peitalin/vim-jsx-typescript"
on_ft = ["typescriptreact"]

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = ["rust"]
hook_post_source = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = "ElmCast/elm-vim"
on_ft = ["elm"]
hook_post_source = '''
let g:elm_setup_keybindings = 0
'''

[[plugins]]
repo = "hashivim/vim-terraform"
on_ft = ["tf"]

[[plugins]]
repo = "dart-lang/dart-vim-plugin"
on_ft = ["dart"]
